#!/usr/bin/env python3
"""
Copilot Code Review Script
Standardized for all repositories.
"""

import os
import requests
import sys
import random


def get_mock_ai_review(title, files):
    """Generate a mock AI review when real APIs are not available"""
    reviews = [
        "Code looks well-structured. Consider adding more unit tests for edge cases.",
        "Good separation of concerns. The implementation follows clean code principles.",
        "Consider adding error handling for network failures. Overall, solid implementation.",
        "The logic is sound. Consider adding documentation for complex business rules.",
        "Well-written code with good naming conventions. Consider performance optimizations for large datasets.",
    ]
    return random.choice(reviews)


def main():
    pr_number = os.getenv("PR_NUMBER")
    if not pr_number:
        print("ℹ️  No PR number - skipping review")
        return

    print(f"Reviewing PR #{pr_number}...")

    headers = {"Authorization": f"token {os.getenv('GITHUB_TOKEN')}"}
    pr_url = f"https://api.github.com/repos/{os.getenv('GITHUB_OWNER')}/{os.getenv('GITHUB_REPO')}/pulls/{pr_number}"

    try:
        pr_response = requests.get(pr_url, headers=headers, timeout=30)
        if pr_response.status_code != 200:
            print(f"⚠️  Failed to fetch PR: {pr_response.status_code}")
            return

        pr_data = pr_response.json()
        title = pr_data.get("title", "Unknown PR")

        # Get PR files
        diff_url = f"{pr_url}/files"
        diff_response = requests.get(diff_url, headers=headers, timeout=30)
        files = diff_response.json() if diff_response.status_code == 200 else []
        file_list = [f["filename"] for f in files[:5]] if files else ["No files found"]

        # Check if real AI APIs are available
        openai_key = os.getenv("OPENAI_API_KEY")
        anthropic_key = os.getenv("ANTHROPIC_API_KEY")

        # Configurable Models (Defaults to safe/standard tiers)
        openai_model = os.getenv("OPENAI_MODEL", "gpt-4")
        anthropic_model = os.getenv("ANTHROPIC_MODEL", "claude-3-opus-20240229")

        ai_available = openai_key or anthropic_key
        review_content = ""

        if ai_available:
            print(
                f"✅ AI APIs available - generating intelligent review using {openai_model if openai_key else anthropic_model}"
            )

            # Enhanced Prompt from PRs
            analysis_prompt = f"Analyze this PR: {title}\n\nChanges: {file_list}\n\nProvide a code review focusing on: 1) Code quality 2) Security 3) Performance 4) Best practices"

            try:
                if openai_key:
                    from openai import OpenAI

                    client = OpenAI(api_key=openai_key)
                    response = client.chat.completions.create(
                        model=openai_model,
                        messages=[{"role": "user", "content": analysis_prompt}],
                        max_tokens=500,
                    )
                    review_content = response.choices[0].message.content
                    print(f"✅ {openai_model} analysis complete")
                elif anthropic_key:
                    from anthropic import Anthropic

                    client = Anthropic(api_key=anthropic_key)
                    response = client.messages.create(
                        model=anthropic_model,
                        max_tokens=500,
                        messages=[{"role": "user", "content": analysis_prompt}],
                    )
                    review_content = response.content[0].text
                    print(f"✅ {anthropic_model} analysis complete")
            except Exception as e:
                print(f"⚠️  AI API failed: {e} - using mock review")
                review_content = get_mock_ai_review(title, file_list)
        else:
            print("🔄 Using mock AI review (no API keys configured)")
            review_content = get_mock_ai_review(title, file_list)

        review_body = f"""## 🤖 Copilot Code Review

### Analysis
PR: **{title}**
Model: `{openai_model if openai_key else (anthropic_model if anthropic_key else "Mock")}`

### AI Review
{review_content}

### Recommendations
- Review code for potential issues
- Check test coverage
- Verify security best practices
- Consider performance implications

*Generated by GitHub Copilot*
"""

        comment_url = f"https://api.github.com/repos/{os.getenv('GITHUB_OWNER')}/{os.getenv('GITHUB_REPO')}/issues/{pr_number}/comments"
        response = requests.post(
            comment_url, headers=headers, json={"body": review_body}, timeout=30
        )

        if response.status_code == 201:
            print("✅ Copilot review posted to PR")
        else:
            print(f"⚠️  Failed to post review: {response.status_code}")

    except Exception as e:
        print(f"⚠️  Review failed: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
