// Generated by AI-Enhanced Automation
// Wed Oct 15 12:30:27 CDT 2025


Test Class:
```
import XCTest
@testable import CodingReviewer

class SidebarViewTests: XCTestCase {
    var sut: SidebarView!

    override func setUp() {
        super.setUp()

        let selectedFileURL = URL(fileURLWithPath: "/example/file.swift")
        let showFilePicker = false
        let selectedAnalysisType = AnalysisType.comprehensive
        let currentView = ContentViewType.analysis

        sut = SidebarView(selectedFileURL: selectedFileURL, showFilePicker: showFilePicker, selectedAnalysisType: selectedAnalysisType, currentView: currentView)
    }

    override func tearDown() {
        super.tearDown()

        sut = nil
    }

    // MARK: - Tests

    func test_init() {
        XCTAssertNotNil(sut, "SidebarView should not be nil")
    }

    func test_body_whenShowFilePickerIsFalse() {
        let showFilePicker = false
        sut.showFilePicker = showFilePicker

        XCTAssertEqual(sut.body, VStack(spacing: 0) {
            // Header
            VStack(spacing: 8) {
                Text("CodingReviewer")
                    .font(.title2)
                    .fontWeight(.bold)

                Text("AI-Powered Code Analysis")
                    .font(.caption)
                    .foregroundColor(.secondary)
            }
            .padding()
            .frame(maxWidth: .infinity)
            .background(Color(.windowBackgroundColor))

            Divider()

            // File Selection
            VStack(alignment: .leading, spacing: 12) {
                Text("File Selection")
                    .font(.headline)
                    .padding(.horizontal)

                if let fileURL = sut.selectedFileURL {
                    VStack(alignment: .leading, spacing: 4) {
                        Text("Selected File:")
                            .font(.subheadline)
                            .foregroundColor(.secondary)

                        Text(fileURL.lastPathComponent)
                            .font(.system(.body, design: .monospaced))
                            .lineLimit(1)
                            .truncationMode(.middle)
                    }
                    .padding(.horizontal)
                }

                Button(action: { sut.showFilePicker = true }) {
                    HStack {
                        Image(systemName: "doc.badge.plus")
                        Text(sut.selectedFileURL == nil ? "Select File" : "Change File")
                    }
                    .frame(maxWidth: .infinity)
                }
                .buttonStyle(.borderedProminent)
                .padding(.horizontal)
            }

            Divider()

            // Analysis Type Selection
            VStack(alignment: .leading, spacing: 12) {
                Text("Analysis Type")
                    .font(.headline)
                    .padding(.horizontal)

                Picker("Analysis Type", selection: sut.selectedAnalysisType) {
                    Text("Comprehensive").tag(AnalysisType.comprehensive)
                    Text("Security").tag(AnalysisType.security)
                    Text("Performance").tag(AnalysisType.performance)
                    Text("Bugs").tag(AnalysisType.bugs)
                }
                .pickerStyle(.radioGroup)
                .padding(.horizontal)
            }

            Divider()

            // View Selection
            VStack(alignment: .leading, spacing: 12) {
                Text("View")
                    .font(.headline)
                    .padding(.horizontal)

                Picker("Current View", selection: sut.currentView) {
                    Text("Analysis").tag(ContentViewType.analysis)
                    Text("Documentation").tag(ContentViewType.documentation)
                    Text("Tests").tag(ContentViewType.tests)
                }
                .pickerStyle(.radioGroup)
                .padding(.horizontal)
            }

            Spacer()

            // Footer
            VStack(spacing: 8) {
                Text("Ready for analysis")
                    .font(.caption)
                    .foregroundColor(.secondary)

                if sut.selectedFileURL != nil {
                    Text("File loaded successfully")
                        .font(.caption)
                        .foregroundColor(.green)
                }
            }
            .padding()
        }, "SidebarView body should not be nil when showFilePicker is false")
    }

    func test_body_whenShowFilePickerIsTrue() {
        let showFilePicker = true
        sut.showFilePicker = showFilePicker

        XCTAssertEqual(sut.body, VStack(spacing: 0) {
            // Header
            VStack(spacing: 8) {
                Text("CodingReviewer")
                    .font(.title2)
                    .fontWeight(.bold)

                Text("AI-Powered Code Analysis")
                    .font(.caption)
                    .foregroundColor(.secondary)
            }
            .padding()
            .frame(maxWidth: .infinity)
            .background(Color(.windowBackgroundColor))

            Divider()

            // File Selection
            VStack(alignment: .leading, spacing: 12) {
                Text("File Selection")
                    .font(.headline)
                    .padding(.horizontal)

                if let fileURL = sut.selectedFileURL {
                    VStack(alignment: .leading, spacing: 4) {
                        Text("Selected File:")
                            .font(.subheadline)
                            .foregroundColor(.secondary)

                        Text(fileURL.lastPathComponent)
                            .font(.system(.body, design: .monospaced))
                            .lineLimit(1)
                            .truncationMode(.middle)
                    }
                    .padding(.horizontal)
                }

                Button(action: { sut.showFilePicker = true }) {
                    HStack {
                        Image(systemName: "doc.badge.plus")
                        Text(sut.selectedFileURL == nil ? "Select File" : "Change File")
                    }
                    .frame(maxWidth: .infinity)
                }
                .buttonStyle(.borderedProminent)
                .padding(.horizontal)
            }

            Divider()

            // Analysis Type Selection
            VStack(alignment: .leading, spacing: 12) {
                Text("Analysis Type")
                    .font(.headline)
                    .padding(.horizontal)

                Picker("Analysis Type", selection: sut.selectedAnalysisType) {
                    Text("Comprehensive").tag(AnalysisType.comprehensive)
                    Text("Security").tag(AnalysisType.security)
                    Text("Performance").tag(AnalysisType.performance)
                    Text("Bugs").tag(AnalysisType.bugs)
                }
                .pickerStyle(.radioGroup)
                .padding(.horizontal)
            }

            Divider()

            // View Selection
            VStack(alignment: .leading, spacing: 12) {
                Text("View")
                    .font(.headline)
                    .padding(.horizontal)

                Picker("Current View", selection: sut.currentView) {
                    Text("Analysis").tag(ContentViewType.analysis)
                    Text("Documentation").tag(ContentViewType.documentation)
                    Text("Tests").tag(ContentViewType.tests)
                }
                .pickerStyle(.radioGroup)
                .padding(.horizontal)
            }

            Spacer()

            // Footer
            VStack(spacing: 8) {
                Text("Ready for analysis")
                    .font(.caption)
                    .foregroundColor(.secondary)

                if sut.selectedFileURL != nil {
                    Text("File loaded successfully")
                        .font(.caption)
                        .foregroundColor(.green)
                }
            }
            .padding()
        }, "SidebarView body should not be nil when showFilePicker is true")
    }
}
```
Tests for all public methods:
```
func test_init() {
    XCTAssertNotNil(sut, "SidebarView should not be nil")
}

func test_selectedFileURL() {
    let selectedFileURL = URL(fileURLWithPath: "/example/file.swift")
    sut.selectedFileURL = selectedFileURL
    XCTAssertEqual(sut.selectedFileURL, selectedFileURL)
}

func test_showFilePicker() {
    sut.showFilePicker = true
    XCTAssertTrue(sut.showFilePicker)
}

func test_selectedAnalysisType() {
    let selectedAnalysisType = AnalysisType.comprehensive
    sut.selectedAnalysisType = selectedAnalysisType
    XCTAssertEqual(sut.selectedAnalysisType, selectedAnalysisType)
}

func test_currentView() {
    let currentView = ContentViewType.analysis
    sut.currentView = currentView
    XCTAssertEqual(sut.currentView, currentView)
}
```
Edge cases and error handling:
```
func test_selectedFileURL_nil() {
    sut.selectedFileURL = nil
    XCTAssertNil(sut.selectedFileURL)
}

func test_showFilePicker_false() {
    sut.showFilePicker = false
    XCTAssertFalse(sut.showFilePicker)
}
```
Mock data where appropriate:
```
func test_body_mockData() {
    let selectedFileURL = URL(fileURLWithPath: "/example/file.swift")
    let showFilePicker = false
    let selectedAnalysisType = AnalysisType.comprehensive
    let currentView = ContentViewType.analysis

    sut.selectedFileURL = selectedFileURL
    sut.showFilePicker = showFilePicker
    sut.selectedAnalysisType = selectedAnalysisType
    sut.currentView = currentView

    XCTAssertEqual(sut.body, VStack(spacing: 0) {
        // Header
        VStack(spacing: 8) {
            Text("CodingReviewer")
                .font(.title2)
                .fontWeight(.bold)

            Text("AI-Powered Code Analysis")
                .font(.caption)
                .foregroundColor(.secondary)
        }
        .padding()
        .frame(maxWidth: .infinity)
        .background(Color(.windowBackgroundColor))

        Divider()

        // File Selection
        VStack(alignment: .leading, spacing: 12) {
            Text("File Selection")
                .font(.headline)
                .padding(.horizontal)

            if let fileURL = sut.selectedFileURL {
                VStack(alignment: .leading, spacing: 4) {
                    Text("Selected File:")
                        .font(.subheadline)
                        .foregroundColor(.secondary)

                    Text(fileURL.lastPathComponent)
                        .font(.system(.body, design: .monospaced))
                        .lineLimit(1)
                        .truncationMode(.middle)
                }
                .padding(.horizontal)
            }

            Button(action: { sut.showFilePicker = true }) {
                HStack {
                    Image(systemName: "doc.badge.plus")
                    Text(sut.selectedFileURL == nil ? "Select File" : "Change File")
                }
                .frame(maxWidth: .infinity)
            }
            .buttonStyle(.borderedProminent)
            .padding(.horizontal)
        }

        Divider()

        // Analysis Type Selection
        VStack(alignment: .leading, spacing: 12) {
            Text("Analysis Type")
                .font(.headline)
                .padding(.horizontal)

            Picker("Analysis Type", selection: sut.selectedAnalysisType) {
                Text("Comprehensive").tag(AnalysisType.comprehensive)
                Text("Security").tag(AnalysisType.security)
                Text("Performance").tag(AnalysisType.performance)
                Text("Bugs").tag(AnalysisType.bugs)
            }
            .pickerStyle(.radioGroup)
            .padding(.horizontal)
        }

        Divider()

        // View Selection
        VStack(alignment: .leading, spacing: 12) {
            Text("View")
                .font(.headline)
                .padding(.horizontal)

            Picker("Current View", selection: sut.currentView) {
                Text("Analysis").tag(ContentViewType.analysis)
                Text("Documentation").tag(ContentViewType.documentation)
                Text("Tests").tag(ContentViewType.tests)
            }
            .pickerStyle(.radioGroup)
            .padding(.horizontal)
        }

        Spacer()

        // Footer
        VStack(spacing: 8) {
            Text("Ready for analysis")
                .font(.caption)
                .foregroundColor(.secondary)

            if sut.selectedFileURL != nil {
                Text("File loaded successfully")
                    .font(.caption)
                    .foregroundColor(.green)
            }
        }
        .padding()
    }, "SidebarView body should not be nil when showFilePicker is true")
}
```
